angular.module("app").constant("language", {
    "COORD": "Les coordonnées de ma filleule",
	"NAME": "Nom",
	"LASTNAME": "Prénom",
    "CIVILITY": "Civilité",
    "UNSPECIFIED": "Non spécifié",
    "MISTER" : "Monsieur",
    "MRS": "Madame",
    "ADDRESS1": "Adresse 1",
    "ADDRESS2": "Adresse 2",
    "ZIPCODE": "Code postal",
    "TOWN": "Ville",
    "PHONE": "Téléphone",
    "MAIL": "E-mail",
    "THIRD": "•	Si ce parrainage vient d'une marraine hors réseau, merci d'indiquer ses coordonnées complètes (Nom, Prénom, adresse postale, e-mail et téléphone)",
	"SPONSOR": "Coordonnées marraines hors réseau / commentaires",
    "REQUIRED": "Obligatoire",
	"SEND": "Envoyer",
	"INIT": "Effacer"
});