angular.module("app").constant("language", {
    "SUBTITLE": "Shows <span class=\"realized\">Done</span> and <span class=\"planified\">Booked</span> monthly and weekly for AW17,"
	+ "as well as the <span class=\"histo\">History</span> for the previous year (Y-1)",
	"SUBTITLE_ANIM": "Click on the Consultants name to see her calendar of registered bookings.",
	"TOTAL_MONTH_COUNT": "Number of shows per month",
    "TOTAL_WEEK_COUNT": "Number of shows per week",
    "TOTAL_SEASON_COUNT": "Season total",
    "TOTAL" : "Total",
    "DATE_UPDATED": "Updated on",
    "REALIZED": "Held",
    "REALIZED_SHORT": "Held",
    "PLANIFIED": "Booked",
    "PLANIFIED_SHORT": "Booked",
    "REALIZED_HISTO_SHORT": "Held Y-1",
	"HISTO_SHORT": "Y-1",
    "FORMAT_DATE": "dd/MM/yyyy '-' HH':'mm",
	"SEARCH_ANIM": "Enter the name of a Manager",
	"FR": "France",
	"IE": "Ireland",
	"UK": "England",
	"ES": "Spain",
	"CH": "Swiss",
	"DE": "Germany",
	"AT": "Austria",
	"INTERNATIONAL": "Intl.",
	"TOP10": "Top 5",
	"CURRENT_WEEK": "Current week",
	"W": "Week ",
	"TITLE_ACTIVE": "Rate of active consultants",
	"ACTIVES": "actives",
	"INACTIVES": "inactives",
	"CURRENT_SEASON": "Current season",
	"NEXT_SEASON": "Next season",
	"AH16": "AW16",
	"PE16": "SS16",
	"AH17": "AW17",
	"PE17": "SS17",
	"AH18": "AW18",
	"PE18": "SS18",
	"AH19": "AW19",
	"PE19": "SS19"
});