angular.module("app").constant("language", {
    "SUBTITLE": "Les ateliers <span class=\"realized\">réalisés</span> et <span class=\"planified\">programmés</span> par mois et par semaine, sur AH17"
	+ ", ainsi que <span class=\"histo\">l’historique des ateliers</span> réalisés l’année précédente (N-1).",
	"SUBTITLE_ANIM": "En cliquant sur le nom d’une conseillère, accédez à son agenda détaillé.",
	"TOTAL_MONTH_COUNT": "Nombre d'ateliers par mois",
    "TOTAL_WEEK_COUNT": "Nombre d'ateliers par semaine",
    "TOTAL_SEASON_COUNT": "Total Saison",
    "TOTAL" : "Total",
    "DATE_UPDATED": "Données mises à jour le",
    "REALIZED": "Réalisé",
    "REALIZED_SHORT": "Réa.",
    "PLANIFIED": "Programmé",
    "PLANIFIED_SHORT": "Prog.",
    "REALIZED_HISTO_SHORT": "Réa. N-1",
	"HISTO_SHORT": "N-1",
    "FORMAT_DATE": "dd/MM/yyyy 'à' HH'h'mm",
	"SEARCH_ANIM": "Entrer le nom d'une animatrice",
	"FR": "France",
	"IE": "Irlande",
	"UK": "Angleterre",
	"ES": "Espagne",
	"CH": "Suisse",
	"DE": "Allemagne",
	"AT": "Autriche",
	"INTERNATIONAL": "Export",
	"TOP10": "Top 10",
	"TOP10CH": "Top 5",
	"CURRENT_WEEK": "Semaine en cours",
	"W": "S",
	"TITLE_ACTIVE": "Taux de conseillères actives",
	"ACTIVES": "actives",
	"INACTIVES": "inactives",
	"CURRENT_SEASON": "Saison en cours",
	"NEXT_SEASON": "Saison suivante",
	"AH16": "AH16",
	"PE16": "PE16",
	"AH17": "AH17",
	"PE17": "PE17",
	"AH18": "AH18",
	"PE18": "PE18",
	"AH19": "AH19",
	"PE19": "PE19"
});