angular.module("app").constant("language", {
    "SUBTITLE": "Die <span class=\"realized\">gehaltenen</span> und <span class=\"planified\">gebuchten</span> Workshops je Monat und Woche in HW17,"
    + " sowie inhellrosa unterlegt, die <span class=\"histo\">gehaltenen Workshops der gleichen Saison im Vorjahr (J-1)</span>.",
	"SUBTITLE_ANIM": "Beim Anklicken des Namens einer Beraterin ist deren detaillierte Agenda erhältlich.",
	"TOTAL_MONTH_COUNT": "Monatliche WS Anzahl",
    "TOTAL_WEEK_COUNT": "Wöchentliche WS Anzahl",
    "TOTAL_SEASON_COUNT": "Gesamtanzahl WS in der Saison",
    "TOTAL" : "G-Betrag",
    "DATE_UPDATED": "Aktualisierung vom",
    "REALIZED": "Eing.",
    "REALIZED_SHORT": "Eing.",
    "PLANIFIED": "Programmiert",
    "PLANIFIED_SHORT": "Gebucht",
    "REALIZED_HISTO_SHORT": "Eing. J-1",
	"HISTO_SHORT": "J-1",
    "FORMAT_DATE": "dd/MM/yyyy '-' hh':'mm",
	"SEARCH_ANIM": "Name eines Managers eingeben",
	"FR": "Frankreich",
	"IE": "Irland",
	"UK": "England",
	"ES": "Spanien",
	"CH": "Suisse",
	"DE": "Deutschland",
	"AT": "Österreich",
	"INTERNATIONAL": "Export",
	"TOP10": "Top 5",
	"CURRENT_WEEK": "laufende Woche",
	"W": "KW ",
	"TITLE_ACTIVE": "Anteil von aktiven Beraterinnen",
	"ACTIVES": "aktive",
	"INACTIVES": "inaktive",
	"CURRENT_SEASON": "laufende Saison",
	"NEXT_SEASON": "nächste Saison",
	"AH16": "HW16",
	"PE16": "SS16",
	"AH17": "HW17",
	"PE17": "SS17",
	"AH18": "HW18",
	"PE18": "SS18",
	"AH19": "HW19",
	"PE19": "SS19"
});