angular.module("app").constant("language", {
    "SUBTITLE": "Los ateliers <span class=\"realized\">realizados</span> y <span class=\"planified\">fijados</span> por mes y semana en OI17,"
		+ " asi como <span class=\"histo\">el historico de los ateliers</span> realizados el año antes (A-1).",
	"SUBTITLE_ANIM": "Haz un clic en el nombre de la asesora y encuentra su programacion detallada.",
	"TOTAL_MONTH_COUNT": "Numero de Ateliers por mes",
    "TOTAL_WEEK_COUNT": "Numero de Ateliers por semana",
    "TOTAL_SEASON_COUNT": "Total temporada",
    "TOTAL" : "Total",
    "DATE_UPDATED": "Actualizado en el",
    "REALIZED": "Realizado",
    "REALIZED_SHORT": "Rea.",
    "PLANIFIED": "Fijado",
    "PLANIFIED_SHORT": "Fijado",
    "REALIZED_HISTO_SHORT": "Rea. A-1",
	"HISTO_SHORT": "A-1",
    "FORMAT_DATE": "dd/MM/yyyy '-' HH':'mm",
	"SEARCH_ANIM": "Indicar el nombre de una Responsable",
	"FR": "Francia",
	"IE": "Irlanda",
	"UK": "Inglaterra",
	"ES": "España",
	"CH": "Suiza",
	"DE": "Alemania",
	"AT": "Austria",
	"TOP10": "Top 5",
	"INTERNATIONAL": "Export",
	"CURRENT_WEEK": "Semana pendiente",
	"W": "S",
	"TITLE_ACTIVE": "Tasa de asesoras activas",
	"ACTIVES": "activas",
	"INACTIVES": "inactivas",
	"CURRENT_SEASON": "Temporada pendiente",
	"NEXT_SEASON": "Proxima Temporada",
	"AH16": "OI16",
	"PE16": "PV16",
	"AH17": "OI17",
	"PE17": "PV17",
	"AH18": "OI18",
	"PE18": "PV18",
	"AH19": "OI19",
	"PE19": "PV19"
});